/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_pocolor_traincraft_engine_Engine */

#ifndef _Included_me_pocolor_traincraft_engine_Engine
#define _Included_me_pocolor_traincraft_engine_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_pocolor_traincraft_engine_Engine
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_pocolor_traincraft_engine_Engine_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
