#pragma once
#include <iostream>
#include <sstream>
#include <cstdlib>

namespace TMP {

    // ===== Interní helper =====
    template<typename... Args>
    std::string buildMessage(Args&&... args) {
        std::ostringstream oss;
        (oss << ... << args); // fold expression (C++17)
        return oss.str();
    }

    // ===== LOG =====
    template<typename... Args>
    void log(Args&&... args) {
        std::cout << "[LOG] "
                  << buildMessage(std::forward<Args>(args)...)
                  << std::endl;
    }

    // ===== ERROR =====
    template<typename... Args>
    void logError(Args&&... args) {
        std::cerr << "[ERROR] "
                  << buildMessage(std::forward<Args>(args)...)
                  << std::endl;
    }

    /* ^^^ LOGGING GENERATED BY AI ^^^ */

} // namespace TMP